fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        obtao_blog:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                category:
                    mappings:
                        id:
                            type: integer
                        label : ~
                    persistence:
                        driver: orm
                        model: Obtao\BlogBundle\Entity\Category
                        finder: ~
                        provider: ~
                        listener: ~
                article:
                    mappings:
                        id:
                            type: integer
                        authors :
                            type : nested
                            properties :
                                firstname :
                                    index_analyzer : custom_analyzer
                                    search_analyzer : custom_search_analyzer
                                surname :
                                    index_analyzer : custom_analyzer
                                    search_analyzer : custom_search_analyzer
                                id: ~
                        category :
                            index : not_analyzed
                        createdAt :
                            type : date
                        content :
                            index_analyzer: custom_analyzer
                            search_analyzer : custom_search_analyzer
                        publishedAt :
                            type : date
                        published :
                            type : boolean
                        tags : ~
                        title:
                            boost: 6
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                    persistence:
                        driver: orm
                        model: Obtao\BlogBundle\Entity\Article
                        elastica_to_model_transformer:
                            service: obtao.transformers.elastica.article
                        finder: ~
                        provider: ~
                        listener: ~
                    _parent:
                        type : "category"
                        identifier: "id"
                        property : "category"
